# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 342f80eaf55803b753a7276251ddb8802b1f1c42209431ff92b86616ca2bdf2603db7a526418edbcd5991d84092da3e7228a59c33a0afea2ad8f352fce5ba552

test:
  secret_key_base: cd10a3cf90b4460dc466a388e9e6e6766db70dfdb606d0153389b603d80e3d735a1ebdd286881fdb440454e93272da256139bf5e15ba4189fc7393a44723057a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
